Add requirements file and automated jobs for macOS setup

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,7 +49,7 @@ jobs:
           pip install --upgrade astropy  # Installed version incompatible with numpy 1.23.0 [https://github.com/astropy/astropy/issues/12534]
           pip install --ignore-installed PyYAML  # Distutils installed [https://github.com/pypa/pip/issues/5247]
       - name: Install package
-        uses: ./.github/actions/install-cpu
+        uses: ./.github/actions/install
         with:
           editable: true
       - name: Run unit tests and generate coverage report
@@ -81,9 +81,30 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install package
-        uses: ./.github/actions/install-cpu
+        uses: ./.github/actions/install
         with:
           editable: true
+      - name: Run unit tests and generate coverage report
+        run: |
+          set -o pipefail  # To propagate exit code from pytest
+          coverage run --source=graphnet -m pytest tests/ --ignore=tests/data/
+          coverage report -m
+
+
+  build-matrix:
+    name: Unit tests - macOS
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+      - name: Install package
+        uses: ./.github/actions/install
+        with:
+          editable: true
+          hardware: "macOS"
       - name: Run unit tests and generate coverage report
         run: |
           set -o pipefail  # To propagate exit code from pytest
