test macos

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,3 +109,23 @@ jobs:
           coverage report -m
       - name: Print available disk space after unit tests
         run: df -h
+
+  build-macos:
+    name: Unit tests - macOS
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+      - name: Install package
+        uses: ./.github/actions/install
+        with:
+          editable: true
+          hardware: "macos"
+      - name: Run unit tests and generate coverage report
+        run: |
+          set -o pipefail  # To propagate exit code from pytest
+          coverage run --source=graphnet -m pytest tests/  --ignore=tests/data/ --ignore=tests/deployment/ --ignore=tests/examples/
+          coverage report -m
